export enum Color {
    SECONDARY = "#313037",
    PRIMARY_2 = "#912EF2",
    PRIMARY = "#6C1BDB",
    GRAY = "rgba(49, 48, 55, 0.5);",
    WHITE = "#FFFFFF",
    RED = "#FD3419",
    BLACK = "#323537",
    PRIMARY_TEXT = "var(--primary-text)",
    PRIMARY_BG = "var(--primary-bg)",
    SECONDARY_BG = "var(--secondary-bg)",
    BORDER = "var(--border)",
    FOOTER = "#F3F3F3",
    COLOR_MAIN = "rgba(49, 48, 55, 0.1)",
}
